name: Weekly Awards Update

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday midnight
  workflow_dispatch: # Allow manual run

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run crawler
        run: bun run index.ts

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json content/ go.mod go.sum
          git commit -m "Weekly report update: $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Hugo
        run: |
          hugo mod tidy
          hugo \
            --gc \
            --minify \
            --baseURL "https://ozkanpakdil.github.io/usa-stocks-indicator/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
